use crate::model::Arch;

pub fn generate(a: &Arch) -> Vec<(String, String)> {
    let mut out: Vec<(String, String)> = Vec::new();

    // out/openapi/<component>.yaml
    for c in &a.components {
        let sync_servers: Vec<&str> = c
            .ports
            .iter()
            .filter(|p| p.ptype == "sync-call" && p.role.as_deref() == Some("server"))
            .map(|p| p.id.as_str())
            .collect();
        if sync_servers.is_empty() {
            continue;
        }
        let mut paths: Vec<String> = Vec::new();
        for e in &a.edges {
            if e.etype != "sync-call" {
                continue;
            }
            if let Some((tc, tp)) = a.resolve_port(&e.to) {
                if tc.id == c.id && sync_servers.contains(&tp.id.as_str()) {
                    if let Some(spec) = &e.spec {
                        for path in extract_paths(spec) {
                            if !paths.contains(&path) {
                                paths.push(path);
                            }
                        }
                    }
                }
            }
        }
        if paths.is_empty() {
            paths.push(format!("/{}", c.id));
        }
        out.push((
            format!("out/openapi/{}.yaml", c.id),
            openapi_doc(&c.id, &paths),
        ));
    }

    out.push(("out/types.ts".to_string(), ts_types()));
    out.push(("out/mocks.json".to_string(), mocks(a)));
    out
}

fn extract_paths(spec: &str) -> Vec<String> {
    let mut v = Vec::new();
    for seg in spec.split_whitespace() {
        if let Some(rest) = seg.strip_prefix("openapi:paths=") {
            for p in rest.split(',') {
                let p = p.trim();
                if p.starts_with('/') {
                    v.push(p.to_string());
                }
            }
        }
    }
    v
}

fn openapi_doc(name: &str, paths: &[String]) -> String {
    let mut s = String::new();
    s.push_str("openapi: 3.0.3\ninfo:\n");
    s.push_str(&format!("  title: {}\n  version: 0.1.0\npaths:\n", name));
    for p in paths {
        s.push_str(&format!("  {}:\n", p));
        s.push_str("    post:\n");
        s.push_str(&format!("      summary: sync-call into {}\n", name));
        s.push_str("      responses:\n        '200':\n          description: OK\n");
    }
    s
}

fn ts_types() -> String {
    let mut s = String::new();
    s.push_str("// Generated by archform\n");
    s.push_str("export type ContractType = 'sync-call' | 'event' | 'data-store' | 'tool-call' | 'model-io' | 'stream';\n\n");
    s.push_str("export interface Arch {\n  version: number;\n  policies: Record<string, Policy>;\n  defaults: Defaults;\n  components: Component[];\n  edges: Edge[];\n}\n\n");
    s.push_str("export interface Policy {\n  ptype: string;\n  scheme?: string;\n  pdp?: string;\n}\n\n");
    s.push_str("export interface Defaults {\n  edges: string[];\n  nodes: Record<string, Record<string, string>>;\n}\n\n");
    s.push_str("export interface Component {\n  id: string;\n  kind: string;\n  x: number;\n  y: number;\n  annotations: Record<string, string>;\n  ports: Port[];\n}\n\n");
    s.push_str("export interface Port {\n  id: string;\n  ptype: ContractType;\n  role?: string;\n  spec?: string;\n}\n\n");
    s.push_str("export interface Edge {\n  id: string;\n  from: string;\n  to: string;\n  etype: ContractType;\n  spec?: string;\n  annotations: string[];\n}\n");
    s
}

fn json_escape(s: &str) -> String {
    let mut o = String::new();
    for ch in s.chars() {
        match ch {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            c => o.push(c),
        }
    }
    o
}

fn mocks(a: &Arch) -> String {
    let mut items: Vec<String> = Vec::new();
    for c in &a.components {
        for p in &c.ports {
            let method = match p.ptype.as_str() {
                "sync-call" => "POST",
                "event" => "PUBLISH",
                "data-store" => "GET",
                "tool-call" => "INVOKE",
                "model-io" => "PROMPT",
                "stream" => "SUBSCRIBE",
                _ => "CALL",
            };
            items.push(format!(
                "    {{\n      \"component\": \"{}\",\n      \"port\": \"{}\",\n      \"ptype\": \"{}\",\n      \"method\": \"{}\",\n      \"path\": \"/mock/{}/{}\",\n      \"response\": {{\"schema\": \"placeholder\"}}\n    }}",
                json_escape(&c.id),
                json_escape(&p.id),
                json_escape(&p.ptype),
                method,
                json_escape(&c.id),
                json_escape(&p.id)
            ));
        }
    }
    format!("{{\n  \"mocks\": [\n{}\n  ]\n}}\n", items.join(",\n"))
}
